In [1]:
import sys
import numpy as np

In [9]:
a  = np.array([1,2,3,4])
a[0:3]

array([1, 2, 3])

In [12]:
a[1:]

array([2, 3, 4])

In [14]:
a[::3]

array([1, 4])

In [16]:
a.dtype

dtype('int64')

In [17]:
aFloat= a.astype(float)

In [20]:
aFloat.dtype

dtype('float64')

In [21]:
aFloat

array([1., 2., 3., 4.])

In [24]:
m = np.array([[1,2,3],[4,5,6]])
m.shape

(2, 3)

In [38]:
m_3d = m.reshape((2, 1, 3))

In [39]:
m_3d.ndim

3

In [40]:
m_3d.size

6

In [45]:
m[1]

array([4, 5, 6])

In [44]:
m[:, :2]

array([[1, 2],
       [4, 5]])

In [48]:
m[0] = np.array([10, 11, 12])
m

array([[10, 11, 12],
       [ 4,  5,  6]])

In [49]:
m.sum()

48

In [50]:
m.mean()

8.0

In [54]:
m.sum(axis = 0)

array([14, 16, 18])

In [55]:
m * 3

array([[30, 33, 36],
       [12, 15, 18]])

In [60]:
m >= 7

array([[ True,  True,  True],
       [False, False, False]])

In [66]:
n= np.random.randint(100,size=(5,8))
n

array([[51, 57, 13, 25, 17,  2, 47, 13],
       [82, 53, 94, 48, 89,  6, 88, 61],
       [67, 16, 17, 88, 11, 71, 32, 68],
       [64,  7, 52, 92, 81, 39, 77, 71],
       [99, 61, 24, 54, 95,  4, 66,  7]])

In [67]:
n[n > 41 ]

array([51, 57, 47, 82, 53, 94, 48, 89, 88, 61, 67, 88, 71, 68, 64, 52, 92,
       81, 77, 71, 99, 61, 54, 95, 66])

In [69]:
a= np.random.randint(20,size=(3,3))
a

array([[ 4,  9, 17],
       [ 3,  6, 11],
       [ 9,  2, 13]])

In [70]:
b= np.random.randint(10,size=(3,3))
b

array([[4, 9, 5],
       [8, 7, 6],
       [1, 3, 9]])

In [72]:
a.dot(b)

array([[105, 150, 227],
       [ 71, 102, 150],
       [ 65, 134, 174]])

In [73]:
a @ b

array([[105, 150, 227],
       [ 71, 102, 150],
       [ 65, 134, 174]])

In [75]:
np.random.rand(2, 4)

array([[0.97758873, 0.9023744 , 0.27335534, 0.20515584],
       [0.05755031, 0.85460913, 0.124815  , 0.82942604]])

In [76]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [77]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [79]:
np.linspace(1, 30, 20)

array([ 1.        ,  2.52631579,  4.05263158,  5.57894737,  7.10526316,
        8.63157895, 10.15789474, 11.68421053, 13.21052632, 14.73684211,
       16.26315789, 17.78947368, 19.31578947, 20.84210526, 22.36842105,
       23.89473684, 25.42105263, 26.94736842, 28.47368421, 30.        ])

In [80]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [85]:
np.eye(3, 3, k = 1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [91]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes
